### ISSUE TITLE
Can't run SVGViewDemo

### ISSUE THREAD

**Issue by bnsports** [GLMap/svgpb#1]
Hi. I'm trying to install svgpb tool by using this instruction:

> SVGView
> 
> Set of tools to render simple SVG files on iOS using Core Graphics
> 
> Prerequisites
> 
> To download and build protobuf just run make.
> 
> Build
> 
> svg2pb is used in Build Rule of SVGViewDemo target to create protobuf version of SVG images and it should be build first.
> 
> Launch Archive action on svg2pb target to build and install svg2pb into /usr/local/bin. You may need to update Developer Team to build it.
> Run SVGViewDemo application

I'm successfully download and install protobuf by running make command.
After that I'm launch archive action on svg2pb target and it's archived successfully.
Then I'm trying to run SVGViewDemo but it failed.

> /bin/sh: /usr/local/bin/svg2pb: is a directory
> Command /bin/sh failed with exit code 126

To fix it I'm replace this code in script on the Build Rules tab:

> /usr/local/bin/svg2pb "$INPUT_FILE_PATH" "$TARGET_BUILD_DIR/$WRAPPER_NAME/$INPUT_FILE_BASE.svgpb"

with this (just add path to svg2pb file, not directory):

> /usr/local/bin/svg2pb/svg2pb "$INPUT_FILE_PATH" "$TARGET_BUILD_DIR/$WRAPPER_NAME/$INPUT_FILE_BASE.svgpb"

But it still failed :

<img width="1399" alt="screen shot 2017-05-04 at 14 53 35" src="https://cloud.githubusercontent.com/assets/5768379/25694603/8e122c2c-30d9-11e7-9a65-7be0d818d636.png">

Hope my explanation clearly, if not please ask for additional information.

**Comment by molind** [comment]
Seems you somehow created folder at `/usr/local/svg2pb` and during install phase `svg2pb` runs `cp $TARGET_BUILD_DIR/$EXECUTABLE_NAME $INSTALL_PATH/$EXECUTABLE_NAME` it copies `svg2pb` into folder named svg2pb instead of correct location. `/usr/local/svg2pb`.

Please remove `/usr/local/svg2pb` folder and try to install it again.

Second your issue is fixed in f32099312884e1babe61504ee2a9ca9791f3b90a. Libraries and and header search path was incorrect.
